### ISSUE TITLE
Wrong product title is fetched.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/MagentoConnectorBundle#6]
Currently category title is loaded for product title.

**Comment by GrandLTU** [comment]
Problem seems to be elsewhere: if wrong shop id is configured all products are fetched but without attributes.

**Comment by mindaugasrukas** [comment]
Related to: https://github.com/ongr-io/ConnectionsBundle/issues/88

**Comment by tfe2012** [comment]
Resolved with https://github.com/ongr-io/MagentoConnectorBundle/pull/31
